## NumPy = Numerical Python. It's the foundation of Data Science, Machine Learning, Deep Learning, Pandas, TensorFlow, and PyTorch.

### Python lists are flexible but slow for numerical computations.
NumPy provides:

- Faster calculations
- Multi-dimensional arrays
- Mathematical operations
- Matrix operations
- Statistical functions

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

(2, 4)
2
8
int64


In [7]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 2))


array([[1., 1.],
       [1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange(1, 13)

print(arr.reshape(3, 4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [24]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4])

[2 3 4]


In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [28]:
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

15
3.0
5
1


In [29]:
np.random.rand(3)

array([0.36910711, 0.20754806, 0.95956433])

In [30]:
np.random.randint(1, 10, 5)

array([3, 7, 1, 1, 9], dtype=int32)

In [ ]:
arr = np.array([10,20,60,80,45,90])

print(arr[arr > 50])