In [2]:
import numpy as np
arr = np.array([5,2,9,1,3]) #sorting

print(np.sort(arr))

[1 2 3 5 9]


In [3]:
arr = np.array([10,20,30,40,50]) #filtering

print(arr[arr > 30])

[40 50]


In [4]:
arr = np.array([1,2,3,4,5]) #boolean masking

mask = arr % 2 == 0

print(mask)
print(arr[mask])

[False  True False  True False]
[2 4]


In [5]:
arr = np.array([ #broadcasting
    [1,2,3],
    [4,5,6]
])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [6]:
A = np.array([ #matrix operations
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [7]:
A = np.array([ #transpose
    [1,2,3],
    [4,5,6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
A = np.array([   #inverse matrix
    [1,2],
    [3,4]
])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
A = np.array([  #det
    [1,2],
    [3,4]
])

print(np.linalg.det(A))

-2.0000000000000004


In [10]:
a = np.array([1,2,3]) #concat
b = np.array([4,5,6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [11]:
a = np.array([[1,2]])
b = np.array([[3,4]])

print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [12]:
a = np.array([[1,2]])
b = np.array([[3,4]])

print(np.hstack((a,b)))

[[1 2 3 4]]


In [13]:
arr = np.array([1,2,2,3,4,4])

print(np.unique(arr))

[1 2 3 4]


In [16]:
arr = np.array([10,20,30,40])

print(np.where(arr[] > 20))

IndexError: index 10 is out of bounds for axis 0 with size 4